/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics;

/**
 * Service definition for Genomics (v1beta).
 *
 * <p>
 * Provides access to Genomics data.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GenomicsRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 */
@SuppressWarnings("javadoc")
public class Genomics extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc-SNAPSHOT of the Genomics API library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://www.googleapis.com/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "genomics/v1beta/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Genomics(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Genomics(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Datasets collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Genomics genomics = new Genomics(...);}
   *   {@code Genomics.Datasets.List request = genomics.datasets().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Datasets datasets() {
    return new Datasets();
  }

  /**
   * The "datasets" collection of methods.
   */
  public class Datasets {

    /**
     * Gets a dataset by ID.
     *
     * Create a request for the method "datasets.get".
     *
     * This request holds the parameters needed by the genomics server.  After setting any optional
     * parameters, call the {@link Get#execute()} method to invoke the remote operation.
     *
     * @param datasetId The ID of the dataset.
     * @return the request
     */
    public Get get(java.lang.String datasetId) throws java.io.IOException {
      Get result = new Get(datasetId);
      initialize(result);
      return result;
    }

    public class Get extends GenomicsRequest<com.google.api.services.genomics.model.GetDatasetResponse> {

      private static final String REST_PATH = "datasets/{datasetId}";

      /**
       * Gets a dataset by ID.
       *
       * Create a request for the method "datasets.get".
       *
       * This request holds the parameters needed by the the genomics server.  After setting any
       * optional parameters, call the {@link Get#execute()} method to invoke the remote operation. <p>
       * {@link Get#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param datasetId The ID of the dataset.
       * @since 1.13
       */
      protected Get(java.lang.String datasetId) {
        super(Genomics.this, "GET", REST_PATH, null, com.google.api.services.genomics.model.GetDatasetResponse.class);
        this.datasetId = com.google.api.client.util.Preconditions.checkNotNull(datasetId, "Required parameter datasetId must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Get setAlt(java.lang.String alt) {
        return (Get) super.setAlt(alt);
      }

      @Override
      public Get setFields(java.lang.String fields) {
        return (Get) super.setFields(fields);
      }

      @Override
      public Get setKey(java.lang.String key) {
        return (Get) super.setKey(key);
      }

      @Override
      public Get setOauthToken(java.lang.String oauthToken) {
        return (Get) super.setOauthToken(oauthToken);
      }

      @Override
      public Get setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Get) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Get setQuotaUser(java.lang.String quotaUser) {
        return (Get) super.setQuotaUser(quotaUser);
      }

      @Override
      public Get setUserIp(java.lang.String userIp) {
        return (Get) super.setUserIp(userIp);
      }

      /** The ID of the dataset. */
      @com.google.api.client.util.Key
      private java.lang.String datasetId;

      /** The ID of the dataset.
       */
      public java.lang.String getDatasetId() {
        return datasetId;
      }

      /** The ID of the dataset. */
      public Get setDatasetId(java.lang.String datasetId) {
        this.datasetId = datasetId;
        return this;
      }

      @Override
      public Get set(String parameterName, Object value) {
        return (Get) super.set(parameterName, value);
      }
    }
    /**
     * Updates a dataset
     *
     * Create a request for the method "datasets.update".
     *
     * This request holds the parameters needed by the genomics server.  After setting any optional
     * parameters, call the {@link Update#execute()} method to invoke the remote operation.
     *
     * @param datasetId The ID of the dataset to update.
     * @param content the {@link com.google.api.services.genomics.model.UpdateDatasetRequest}
     * @return the request
     */
    public Update update(java.lang.String datasetId, com.google.api.services.genomics.model.UpdateDatasetRequest content) throws java.io.IOException {
      Update result = new Update(datasetId, content);
      initialize(result);
      return result;
    }

    public class Update extends GenomicsRequest<com.google.api.services.genomics.model.UpdateDatasetResponse> {

      private static final String REST_PATH = "datasets/{datasetId}";

      /**
       * Updates a dataset
       *
       * Create a request for the method "datasets.update".
       *
       * This request holds the parameters needed by the the genomics server.  After setting any
       * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
       * <p> {@link
       * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param datasetId The ID of the dataset to update.
       * @param content the {@link com.google.api.services.genomics.model.UpdateDatasetRequest}
       * @since 1.13
       */
      protected Update(java.lang.String datasetId, com.google.api.services.genomics.model.UpdateDatasetRequest content) {
        super(Genomics.this, "PUT", REST_PATH, content, com.google.api.services.genomics.model.UpdateDatasetResponse.class);
        this.datasetId = com.google.api.client.util.Preconditions.checkNotNull(datasetId, "Required parameter datasetId must be specified.");
      }

      @Override
      public Update setAlt(java.lang.String alt) {
        return (Update) super.setAlt(alt);
      }

      @Override
      public Update setFields(java.lang.String fields) {
        return (Update) super.setFields(fields);
      }

      @Override
      public Update setKey(java.lang.String key) {
        return (Update) super.setKey(key);
      }

      @Override
      public Update setOauthToken(java.lang.String oauthToken) {
        return (Update) super.setOauthToken(oauthToken);
      }

      @Override
      public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Update) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Update setQuotaUser(java.lang.String quotaUser) {
        return (Update) super.setQuotaUser(quotaUser);
      }

      @Override
      public Update setUserIp(java.lang.String userIp) {
        return (Update) super.setUserIp(userIp);
      }

      /** The ID of the dataset to update. */
      @com.google.api.client.util.Key
      private java.lang.String datasetId;

      /** The ID of the dataset to update.
       */
      public java.lang.String getDatasetId() {
        return datasetId;
      }

      /** The ID of the dataset to update. */
      public Update setDatasetId(java.lang.String datasetId) {
        this.datasetId = datasetId;
        return this;
      }

      @Override
      public Update set(String parameterName, Object value) {
        return (Update) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Jobs collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Genomics genomics = new Genomics(...);}
   *   {@code Genomics.Jobs.List request = genomics.jobs().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Jobs jobs() {
    return new Jobs();
  }

  /**
   * The "jobs" collection of methods.
   */
  public class Jobs {

    /**
     * Gets a job by ID.
     *
     * Create a request for the method "jobs.get".
     *
     * This request holds the parameters needed by the genomics server.  After setting any optional
     * parameters, call the {@link Get#execute()} method to invoke the remote operation.
     *
     * @param jobId The ID of the job to get.
     * @return the request
     */
    public Get get(java.lang.String jobId) throws java.io.IOException {
      Get result = new Get(jobId);
      initialize(result);
      return result;
    }

    public class Get extends GenomicsRequest<com.google.api.services.genomics.model.GetJobResponse> {

      private static final String REST_PATH = "jobs/{jobId}";

      /**
       * Gets a job by ID.
       *
       * Create a request for the method "jobs.get".
       *
       * This request holds the parameters needed by the the genomics server.  After setting any
       * optional parameters, call the {@link Get#execute()} method to invoke the remote operation. <p>
       * {@link Get#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param jobId The ID of the job to get.
       * @since 1.13
       */
      protected Get(java.lang.String jobId) {
        super(Genomics.this, "GET", REST_PATH, null, com.google.api.services.genomics.model.GetJobResponse.class);
        this.jobId = com.google.api.client.util.Preconditions.checkNotNull(jobId, "Required parameter jobId must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Get setAlt(java.lang.String alt) {
        return (Get) super.setAlt(alt);
      }

      @Override
      public Get setFields(java.lang.String fields) {
        return (Get) super.setFields(fields);
      }

      @Override
      public Get setKey(java.lang.String key) {
        return (Get) super.setKey(key);
      }

      @Override
      public Get setOauthToken(java.lang.String oauthToken) {
        return (Get) super.setOauthToken(oauthToken);
      }

      @Override
      public Get setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Get) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Get setQuotaUser(java.lang.String quotaUser) {
        return (Get) super.setQuotaUser(quotaUser);
      }

      @Override
      public Get setUserIp(java.lang.String userIp) {
        return (Get) super.setUserIp(userIp);
      }

      /** The ID of the job to get. */
      @com.google.api.client.util.Key
      private java.lang.String jobId;

      /** The ID of the job to get.
       */
      public java.lang.String getJobId() {
        return jobId;
      }

      /** The ID of the job to get. */
      public Get setJobId(java.lang.String jobId) {
        this.jobId = jobId;
        return this;
      }

      /** The Google Cloud project ID. */
      @com.google.api.client.util.Key
      private java.lang.Long projectId;

      /** The Google Cloud project ID.
       */
      public java.lang.Long getProjectId() {
        return projectId;
      }

      /** The Google Cloud project ID. */
      public Get setProjectId(java.lang.Long projectId) {
        this.projectId = projectId;
        return this;
      }

      @Override
      public Get set(String parameterName, Object value) {
        return (Get) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Reads collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Genomics genomics = new Genomics(...);}
   *   {@code Genomics.Reads.List request = genomics.reads().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Reads reads() {
    return new Reads();
  }

  /**
   * The "reads" collection of methods.
   */
  public class Reads {

    /**
     * Gets a list of reads matching the criteria.
     *
     * Create a request for the method "reads.list".
     *
     * This request holds the parameters needed by the genomics server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.google.api.services.genomics.model.ListReadsRequest}
     * @return the request
     */
    public List list(com.google.api.services.genomics.model.ListReadsRequest content) throws java.io.IOException {
      List result = new List(content);
      initialize(result);
      return result;
    }

    public class List extends GenomicsRequest<com.google.api.services.genomics.model.ListReadsResponse> {

      private static final String REST_PATH = "reads/search";

      /**
       * Gets a list of reads matching the criteria.
       *
       * Create a request for the method "reads.list".
       *
       * This request holds the parameters needed by the the genomics server.  After setting any
       * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
       * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.google.api.services.genomics.model.ListReadsRequest}
       * @since 1.13
       */
      protected List(com.google.api.services.genomics.model.ListReadsRequest content) {
        super(Genomics.this, "POST", REST_PATH, content, com.google.api.services.genomics.model.ListReadsResponse.class);
      }

      @Override
      public List setAlt(java.lang.String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(java.lang.String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(java.lang.String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(java.lang.String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(java.lang.String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(java.lang.String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Readsets collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Genomics genomics = new Genomics(...);}
   *   {@code Genomics.Readsets.List request = genomics.readsets().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Readsets readsets() {
    return new Readsets();
  }

  /**
   * The "readsets" collection of methods.
   */
  public class Readsets {

    /**
     * Creates readsets by asynchronously importing the provided information.
     *
     * Create a request for the method "readsets.import".
     *
     * This request holds the parameters needed by the genomics server.  After setting any optional
     * parameters, call the {@link GenomicsImport#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.google.api.services.genomics.model.ImportReadsetsRequest}
     * @return the request
     */
    public GenomicsImport genomicsImport(com.google.api.services.genomics.model.ImportReadsetsRequest content) throws java.io.IOException {
      GenomicsImport result = new GenomicsImport(content);
      initialize(result);
      return result;
    }

    public class GenomicsImport extends GenomicsRequest<com.google.api.services.genomics.model.ImportReadsetsResponse> {

      private static final String REST_PATH = "readsets/import";

      /**
       * Creates readsets by asynchronously importing the provided information.
       *
       * Create a request for the method "readsets.import".
       *
       * This request holds the parameters needed by the the genomics server.  After setting any
       * optional parameters, call the {@link GenomicsImport#execute()} method to invoke the remote
       * operation. <p> {@link GenomicsImport#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.google.api.services.genomics.model.ImportReadsetsRequest}
       * @since 1.13
       */
      protected GenomicsImport(com.google.api.services.genomics.model.ImportReadsetsRequest content) {
        super(Genomics.this, "POST", REST_PATH, content, com.google.api.services.genomics.model.ImportReadsetsResponse.class);
      }

      @Override
      public GenomicsImport setAlt(java.lang.String alt) {
        return (GenomicsImport) super.setAlt(alt);
      }

      @Override
      public GenomicsImport setFields(java.lang.String fields) {
        return (GenomicsImport) super.setFields(fields);
      }

      @Override
      public GenomicsImport setKey(java.lang.String key) {
        return (GenomicsImport) super.setKey(key);
      }

      @Override
      public GenomicsImport setOauthToken(java.lang.String oauthToken) {
        return (GenomicsImport) super.setOauthToken(oauthToken);
      }

      @Override
      public GenomicsImport setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GenomicsImport) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GenomicsImport setQuotaUser(java.lang.String quotaUser) {
        return (GenomicsImport) super.setQuotaUser(quotaUser);
      }

      @Override
      public GenomicsImport setUserIp(java.lang.String userIp) {
        return (GenomicsImport) super.setUserIp(userIp);
      }

      @Override
      public GenomicsImport set(String parameterName, Object value) {
        return (GenomicsImport) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Genomics}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Genomics}. */
    @Override
    public Genomics build() {
      return new Genomics(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GenomicsRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGenomicsRequestInitializer(
        GenomicsRequestInitializer genomicsRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(genomicsRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
