/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics.model;

/**
 * Model definition for GetJobResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Genomics API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 */
@SuppressWarnings("javadoc")
public final class GetJobResponse extends com.google.api.client.json.GenericJson {

  /**
   * A more detailed description of this job's current status.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The job ID.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The status of this job.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * A more detailed description of this job's current status.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * A more detailed description of this job's current status.
   * @param description description or {@code null} for none
   */
  public GetJobResponse setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * The job ID.
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * The job ID.
   * @param id id or {@code null} for none
   */
  public GetJobResponse setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * The status of this job.
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * The status of this job.
   * @param status status or {@code null} for none
   */
  public GetJobResponse setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  @Override
  public GetJobResponse set(String fieldName, Object value) {
    return (GetJobResponse) super.set(fieldName, value);
  }

  @Override
  public GetJobResponse clone() {
    return (GetJobResponse) super.clone();
  }

}
